### PR TITLE
add logs the detailed error message in php

### PR DESCRIPTION
**Pull request by ColdeZhang**
It really takes me time to find out why i can't host web standalone with just "Failed to connect to database".

Then i added the log detail, everything just be cleared: `NOTICE: PHP message: could not find driver`

So I think it's necessary to log err details for solving problems...

### CODE REVIEW

**Review by TBlueF — APPROVED** [review]

**Review by TBlueF — CHANGES_REQUESTED** [review]
Actually, can we add this to the other errors thrown in this php-file as well, please? :)

**Comment by ColdeZhang** [comment]
> Actually, can we add this to the other errors thrown in this php-file as well, please? :)

That's a reasonable idea. I will made this PR modified soon.

**Review by TBlueF — CHANGES_REQUESTED** [review]
Ah sorry,.. but we can not print the full error in the response that is actually sent back to the client, because the error could contain sensitive information.
What i meant was to still use the `error_log()` method you used in the first commit, just for every error, while still sending the generic error message back to the browser =)

**Comment by ColdeZhang** [comment]
> Ah sorry,.. but we can not print the full error in the response that is actually sent back to the client, because the error could contain sensitive information.
> 
> What i meant was to still use the `error_log()` method you used in the first commit, just for every error, while still sending the generic error message back to the browser =)

Oh, sry I forgot that. Wait a minute

**Review by TBlueF — APPROVED** [review]
Thanks a lot! :)

**Pull request merged**
