### PR TITLE
Update zh_TW.conf

### PR DESCRIPTION
**Pull request by TWME-TW**
It's been a long time since my [last translation](https://discord.com/channels/665868367416131594/751804128749027421/825958061940277298), I found some new strings

### CODE REVIEW

**Review by TBlueF — CHANGES_REQUESTED** [review]
You have added `"` to the config-keys everywhere .. e.g.:
```hocon
 "settings": {
    "title": "設定",
    "button": "設定"
  },
 ```
 instead of 
 ```hocon
  settings: {
    title: "設定",
    button: "設定"
  },
```

is there a reason for this? 
Else i would suggest to keep it uniform with the other config formats :)

**Comment by TWME-TW** [comment]
> You have added `"` to the config-keys everywhere .. e.g.:
> 
> ```hocon
>  "settings": {
>     "title": "設定",
>     "button": "設定"
>   },
> ```
> 
> instead of
> 
> ```hocon
>  settings: {
>    title: "設定",
>    button: "設定"
>  },
> ```
> 
> is there a reason for this? Else i would suggest to keep it uniform with the other config formats :)

I think it's because I used the online format checking tool (Note: I later found out that en.conf checking also had a lot of errors and I didn't use it anymore

**Comment by TWME-TW** [comment]
i will change it back

**Comment by TBlueF** [comment]
That's probably because its not `json` but it's `hocon` language =)

**Comment by TWME-TW** [comment]
I also seem to have added some commas, removing...

**Review by TBlueF — APPROVED** [review]

**Comment by TWME-TW** [comment]
i think it's ok now

**Pull request merged**
