### PR TITLE
Show chunk borders

### PR DESCRIPTION
**Pull request by TechnicJelle**
image
image

Should probably add a toggle for it, though.
And a way to customise the colour.

### CODE REVIEW

**Comment by TBlueF** [comment]
Great work!
I'll not merge this without a toggle, though ^^

**Comment by TechnicJelle** [comment]
Aw dangit, I was hoping I wouldn't have to do that myself :p

**Comment by TBlueF** [comment]
I mean .. you can also wait for me to do it, but then it'll end up on the todo and probably take a while to be prioritised ^^

**Comment by TechnicJelle** [comment]
Fair enough...
I guess I'll see how horrific vue.js is, then :p

**Comment by TBlueF** [comment]
If you move the show-chunk-borders variable away from the appState directly to the mapviewer and do it like the `sunlightStrength` and `ambientLight` sliders do it, then you don't need to extend the poor MapViewer constructor =)

And then i am happy :3

**Pull request merged**
